### ISSUE TITLE
Argument count from model.step doesn't match dictionary unpack in train 

### ISSUE THREAD

**Issue by ghexp** [ajarai/fast-weights#2]
In train line 113 the call to model.step() needs to unpack 5 variables, but only unpacks 4.  Results in ValueError below (in Python 2.7). 
```
Traceback (most recent call last):
  File "train.py", line 279, in <module>
    train(FLAGS)
  File "train.py", line 117, in train
    FLAGS.l, FLAGS.e, forward_only=False)
ValueError: too many values to unpack
```
Patched in pull request #1

**Comment by ghexp** [comment]
Fixed in [latest commit](https://github.com/ajarai/fast-weights/commit/9d2a61f5b48e2e2765200ca7472501504fe60830) by removing logits return. Closing
